### ISSUE TITLE
any difference or benchmark with grequest

### ISSUE THREAD

**Issue by litaotao** [ClericPy/torequests#1]
here is [grequest](https://github.com/kennethreitz/grequests)

thanks

**Comment by ClericPy** [comment]
grequests is not good for python3 on windows(gevent raise an error about stdout redirect) , torequests goes under tomorrow (over here https://github.com/madisonmay/Tomorrow )
On other hand, if I use python2.x, I prefer to using gevent+requests instead of grequests...

PS: why don't you speak Chinese...my English is sucky.

sometimes I use tomorrow to rename requests for its async features

``` python
from torequests import tPool
requests=tPool(30)
```

And then, every requests.get in my code will push an async, its easy for using in small projects, and the 'get' will get a nice performance.

**Comment by litaotao** [comment]
哦，soga，那我关了这个 issue 哈，谢谢
